### ISSUE TITLE
Todo's 7th edition

### ISSUE THREAD

**Issue by Jahitko** [talkabit/talkabit#15]
**Suggestions:**
- [x] Sponsors as a carousel for each type.
- [x] Custom mobile navbar (transparency, different toggle icon, etc)
- [ ] Some sort of animation on the landing page

**Loading**
- [x] Reduzir o loading usando o ImageOptim
- [x] Carregando só as imagens essenciais inicialmente (como logo e fundo)
- [x] Adicionar na area dos speakers um subscribe do email (podem usar o MailChimp) e a dizer que avisam quando estiver disponível (esta funcionalidade até é util para os bilhetes). - PASSOU PARA O BACKEND
- [x] Remover o placeholder dos sponsors.

**Melhorar o Call For Papers:**  
- [x] Colocar a informação mais pertinente destacada (deadline, temas)
- [x] Permitir scanar na diagonal o texto
- [x] Diminuir a largura do texto para ficar mais fácil de ler
- [x] Separar por cores as várias secções. 

**Organization:** 
- [ ] Ao carregar não fica selecionado
- [x] Não devia de ter loading (imagens das pessoas devia de ser lazy loaded)
- [ ] No safari quando faço mouse hover primeiro fica quadrado e depois que aparece o logo
- [x]  On hover fix para Edge
- [x] Retificar fotos.
- [x] Adicionar professores ao Program Committe

**Sponsors:**
- [x] Desenhar layout.
- [x] AEFEUP como parceiro. 

**Schedule:**
- [x] Acabar o layout para slots que possam ser extensivos em texto (e.g Companies Pitch) atraves de um botão semelhante ao dos speakers.

**Booklet & Magazine:**
- [x] Definir layout para esta secção. 

**Workshops:**
- [x] Finalizar Layout. 
- [x] Pop Over. 
- [x] Logica.

**Outros:**
- [x] Era bom tentarmos remover o FAQ. O email ja esta la em baixo, podemos separar da location e meter uma opção de contact. Mas nem sei se será necessário ja que esta na cover também. 
- [x] O google maps tem opões desnecessárias como satelite/mapa ou full screen.
- [x] Location não devia de ter loading (se o google maps não carregar, azar, fica cinzento)
- [x] É estranho o menu do topo estar separado. Não dá para perceber a lógica que o separa. Se organization abre uma nova página, então tudo que está do lado direito devia de abrir nova página. Se Location não abre, então devia de ir para o lado esquerdo.
- [x] Subscribe movido para cima.
- [x] Fixed botão do subscribe para mobile.

**Backend:**
- [x] MailChimp
- [x] Google Analytics Setup
- [x] Google Analytics Additional Configurations?
- [x] Firebase Security
