### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jvsonica** [talkabit/talkabit#2]
- [x] add the UP iccon to the end of the first section
- [x] replace the "Talk a bit" image from the header by the talkabit logo 
- [x] include iformation telling that this is the 4th edition of the talkabit conference in the first section 
- [x] Create a FAQ for the site (questions can be copied from the symposium.nebfeupicbas.pt, the site is currently down so a cached try to get a cached version...) 
- [x] correct columns height   
- [x] create a separate page showing all the people involved in the organization of talkabit...  
- [x] implement the template for the schedule
- [x] implement the template for the speakers 
- [x] implement the template for the sponsors ( i think this one still doesn't exist ) 
- [x] try to add the talkabit logo instead of the red marker in the section showing where talkabit is 
- [x] change the navbar transparecy to  0.8/0.9 
- [x] remove shadow present in the main logo 
- [x] the button "Call For Sponsors" is not vertically centered 
- [x] when you click a navbar item or scroll the page the navbar icons should select and unselect according to the showing section
- [x] when the page resized is vertically the talkabit logo and "Call For Sponsors" buttom tramples the header ( a min-width for each section combined with a heigth: 100vh is probabily enough)

**Comment by DDuarte** [comment]
- [ ] update favicon
